---
title: "Kernel machine regression"
author: "Jennifer F. Bobb"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Kernel machine regression}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r options, echo=FALSE}
## if the current working directory is the directory where this file is located rather than the project directory, set the working directory to the project directory
if(grepl("vignettes", getwd())) knitr::opts_knit$set(root.dir = paste(getwd(), "..", sep = "/"))
knitr::opts_chunk$set(fig.width = 5, fig.height = 3, message = FALSE)
```

```{r setup, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
##library(bkmr)
devtools::load_all()
```

```{r load packges, message=FALSE}
library(dplyr)
```


## Simulate some data

```{r simdata}
set.seed(5)
dat <- SimData(n = 100, M = 5, sigsq.true = 0.5, beta.true = 2, HFun = HFun3)
y <- dat$y
expos <- dat$expos
covar <- dat$covar
```

## Conduct overall test

For different kernels
```{r overall}
rho.seq <- c(0.5, 1, 5, 25, 50, 100, 200)
kernel.seq <- data.frame(kernel = c("linear", "quadratic", rep("gaussian", length(rho.seq))), 
                         rho = c(rep(NA, 2), rho.seq))
df <- data.frame()
for (i in 1:nrow(kernel.seq)) {
    kernel <- kernel.seq[i, "kernel"]
    rho <- kernel.seq[i, "rho"]
    tst <- OverallTest(y = y, expos = expos, covar = covar, kernel = kernel, rho = rho)
    df <- rbind(df, data.frame(kernel = kernel, rho = rho, tst))
}
overall.test <- df
```

```{r overall res}
transmute(overall.test, kernel, rho, p = round(p.val, 5))
```

## Conduct garrote kernel test

```{r garrote, message=FALSE}
garrote.test <- GarroteKernelTest(y = y, expos = expos, covar = covar)
```

```{r garrote results}
transmute(garrote.test, pollutant, p = round(p.val, 5))
```





